apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: test-dep
  template:
    metadata:
      labels:
        app: test-dep
    spec:
      hostname: test-dep
      containers:
      - name: test
        image: hashicorp/http-echo
        args:
        - "-text=hello world"
        - "-listen=:8080"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 64Mi
            cpu: "100m"
          requests:
            memory: 32Mi
            cpu: "50m"
      dnsConfig:
        nameservers:
        - 8.8.8.8
        - 8.8.4.4