apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xgl-ing # <-- This is your ingress name. It can be anything you want.
spec:
  ingressClassName: haproxy
  rules:
  - host: YOUR-ENDPOINT.nrp-nautilus.io # <-- Change the endpoint.
    http:
      paths:
      - backend:
          service:
            name: xgl-svc # <-- Change this to the service name you want to use. It must match EXACTLY.
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - YOUR-ENDPOINT.nrp-nautilus.io # <-- Change the endpoint.
---
apiVersion: v1
kind: Service
metadata:
  name: xgl-svc # <-- This is your service name. It can be anything you want.
  labels:
    app: xgl-svc # <-- Also your service name, make it the same as the above.
spec:
  selector:
    app: xgl # <-- Change this to the name of your deployment. It must match EXACTLY.
  ports:
  - name: http
    protocol: TCP
    port: 8080